topic:
  name: OrderRequest

server:
  port: 8089

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      properties:
        # Configuration des sérializers pour les clés et valeurs
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        # Spécification de l'URL du Schema Registry
        schema.registry.url: http://localhost:8081/
